config/routes.rb
Middboard::Application.routes.draw do
  root :to => "pages#home"

  devise_for :users, :path_prefix => 'd'
  resources :users, :only => :show do
    resources :activities
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :user
	has_many :subscriptions
	has_many :followers, :through => :subscriptions , :source => :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :activities
	has_many :subscriptions
	has_many :todos, :through => :subscriptions, :source => :activity

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @user = @activity.user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = current_user.activities.build(params[:activity])
    @activity.user = current_user
    @activity.save
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.build(params[:activity])
    @activity.user = current_user
    @activity.save

    respond_to do |format|
      if @activity.save
        format.html { redirect_to user_path(current_user), notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])
    user = @activity.user

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to user_activity_path(user), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    user = @activity.creator
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to user }
      format.json { head :no_content }
    end
  end

  def add_todo 
    user = User.find(params[:user_id])
    activity = Activity.find(params[:activity_id])
    user.todos.push(activity)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@todos = @user.todos
	end

	def my_activities
		@user = User.find(params[:id])
		@activities = @user.activities
	end

	def my_todos
		@user = User.find(params[:id])
		@todos = @user.todos
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_add_todo.html.erb
<%= form_for current_user.subscriptions.build :activity_id => @activity.id do |f| %>
	<div><%= f.hidden_field :activity_id %></div>
	<div class="actions"><%= f.submit "Do this!" %></div
<% end %>

app/views/activities/_form.html.erb
<%= form_for([current_user, @activity]) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Back', user_activity_path(.user) %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', @activity.user %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<div id="activity_name">
  <%= @activity.name %>
</div>

<p>
  <b>User:</b>
  <%= @activity.user.email %>
</p>

<p>
  <b>Description:</b>
  <%= @activity.description %>
</p>

<div id="add_to_do_button" class="button">
	Do this!
</div>

<%= link_to 'Edit', edit_user_activity_path(@activity) if @activity.user_id == current_user.id %> |
<%= link_to 'Back', user_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Middboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="logo"> Middboard </div>
	<br>
	<div id="header" class="shadow round_small">
		<table id="header_table"><tr>
			<td id="navigation">
				<%= link_to "Home", root_path %>
				&nbsp&nbsp&nbsp&nbsp
				<%= link_to "My Page", current_user %>
			</td>
			<td id="sign_in_out">
				<%= link_to "Sign in", new_user_session_path unless signed_in? %>
				&nbsp&nbsp&nbsp&nbsp
				<%= link_to "Sign up", new_user_registration_path unless signed_in? %>
				<%= link_to "Sign out", destroy_user_session_path, :method => :delete if signed_in? %>
			</td>
			</tr></table>
		</div>
	</div>
	<br>
	<!-- <br> -->
	<div id="main_pane" class="shadow round">
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
Home page!

app/views/users/_my_activities.html.erb
<%= @user == current_user ? "My things activities" : "#{@user.email}'s activities" %>
<% @user.activities.each do |a| %>
	<br>
	<%= link_to a.name, user_activity_path(@user, a) %>
<% end %>
<div id="new_activity_button" class="button">
</div>

app/views/users/_my_todos.html.erb
<%= @user == current_user ? "My things to do" : "#{@user.email}'s things to do" %>
<% @todos.each do |t| %>
	<%= t.name %>
<% end %>

app/views/users/show.html.erb
<div>
	<table id="user_links"><tr>
		<td id="todos_link"> <%= link_to "Todos", "#" %> </td>
		<td id="activities_link"> <%= link_to "Activities", "#" %> </td>
	</tr></table>
</div>

<div id="my_todos">
	<%= render :partial => 'my_todos' %>
</div>

<div id="my_activities">
	<%= render :partial => 'my_activities' %>
</div>